(deftheme clearview-light
  "Created 2017-06-01.")

(custom-theme-set-faces
 'clearview-light
 '(cua-rectangle ((t (:background "gray20" :foreground "white"))))
 '(custom-button ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "gray95"))))
 '(custom-button-mouse ((t (:background "DodgerBlue3" :foreground "white" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((t (:box (:line-width 2 :style pressed-button) :inherit custom-button-mouse))))
 '(custom-group-tag ((t (:inherit variable-pitch :background "gray25" :foreground "white smoke" :weight bold :height 1.25))))
 '(custom-modified ((t (:background "DodgerBlue3" :foreground "white"))))
 '(custom-variable-tag ((t (:weight bold))))
 '(dired-directory ((t (:inherit (font-lock-function-name-face)))))
 '(dired-header ((t (:inherit (font-lock-type-face)))))
 '(dired-symlink ((t (:inherit (font-lock-keyword-face)))))
 '(flycheck-error ((t (:foreground "red" :underline (:color "firebrick" :style wave)))))
 '(flycheck-error-list-column-number ((t (:inherit default))))
 '(flycheck-error-list-error ((t (:inherit flycheck-fringe-error))))
 '(flycheck-error-list-info ((t (:inherit flycheck-fringe-info))))
 '(flycheck-error-list-line-number ((t (:weight bold))))
 '(flycheck-error-list-warning ((t (:inherit flycheck-fringe-warning))))
 '(flycheck-fringe-error ((t (:foreground "red" :weight bold))))
 '(flycheck-fringe-info ((t (:foreground "forest green" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "DodgerBlue1" :weight bold))))
 '(flycheck-info ((t (:underline (:color "forest green" :style wave)))))
 '(flycheck-warning ((t (:underline (:color "gray30" :style wave)))))
 '(font-lock-builtin-face ((t (:foreground "black" :underline t))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "gray60" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "DeepPink3"))))
 '(font-lock-doc-face ((t (:foreground "gray60"))))
 '(font-lock-function-name-face ((t (:foreground "DodgerBlue2" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "black" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit font-lock-regexp-grouping-construct))))
 '(font-lock-regexp-grouping-construct ((t nil)))
 '(font-lock-string-face ((t (:foreground "DarkOrange4"))))
 '(font-lock-type-face ((t (:foreground "dark slate gray" :weight semi-bold))))
 '(font-lock-variable-name-face ((t (:foreground "black"))))
 '(fringe ((t (:background "grey95"))))
 '(highlight ((t (:background "LightCyan1" :foreground "black"))))
 '(isearch ((t (:background "VioletRed3" :foreground "white smoke" :weight bold))))
 '(isearch-fail ((t (:background "DodgerBlue3" :foreground "white smoke" :weight bold))))
 '(ivy-action ((t (:inherit (font-lock-builtin-face)))))
 '(ivy-confirm-face ((t (:foreground "ForestGreen" :inherit (minibuffer-prompt)))))
 '(ivy-current-match ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(ivy-cursor ((t (:background "gray25" :foreground "white"))))
 '(ivy-highlight-face ((t (:inherit (highlight)))))
 '(ivy-match-required-face ((t (:foreground "red" :inherit (minibuffer-prompt)))))
 '(ivy-minibuffer-match-face-1 ((t (:foreground "VioletRed3"))))
 '(ivy-minibuffer-match-face-2 ((t (:foreground "VioletRed3"))))
 '(ivy-minibuffer-match-face-3 ((t (:foreground "VioletRed3"))))
 '(ivy-minibuffer-match-face-4 ((t (:foreground "VioletRed3"))))
 '(ivy-modified-buffer ((t (:inherit (default)))))
 '(ivy-remote ((((class color) (background light)) (:foreground "#110099")) (((class color) (background dark)) (:foreground "#7B6BFF"))))
 '(ivy-subdir ((t (:foreground "black" :weight bold))))
 '(ivy-virtual ((t (:foreground "gray50"))))
 '(lazy-highlight ((t (:background "gray25" :foreground "white" :weight bold))))
 '(link ((t (:foreground "dodgerblue" :underline "black"))))
 '(link-visited ((t (:inherit link :foreground "black"))))
 '(minibuffer-prompt ((t (:foreground "black" :underline nil :weight bold))))
 '(mode-line ((t (:weight bold :background "gray95" :foreground "black" :box (:line-width 1 :color "gray60")))))
 '(mode-line-buffer-id ((t (:weight semi-bold))))
 '(mode-line-buffer-id-inactive ((t (:inherit mode-line-buffer-id :foreground "gray60"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "gray95" :foreground "gray60" :weight normal))))
 '(perspeen-selected-face ((t (:inherit mode-line :background "gray25" :foreground "PaleGreen2" :weight bold))))
 '(perspeen-tab--header-line-active ((t (:weight bold :inherit mode-line))))
 '(perspeen-tab--header-line-inactive ((t (:inherit mode-line :weight normal :background "gray25" :foreground "white"))))
 '(perspeen-tab--powerline-inactive1 ((t (:inherit mode-line :background "gray25" :foreground "white" :weight normal))))
 '(powerline-active1 ((t (:inherit mode-line :background "gray25" :foreground "white" :weight normal))))
 '(powerline-active2 ((t (:inherit mode-line :background "gray25" :foreground "white" :weight normal))))
 '(powerline-inactive1 ((t (:inherit mode-line :background "gray25" :foreground "gray60" :weight normal))))
 '(powerline-inactive2 ((t (:inherit mode-line :background "gray25" :foreground "white" :weight normal))))
 '(region ((t (:background "gray93" :distant-foreground "black"))))
 '(secondary-selection ((t (:inherit highlight))))
 '(show-paren-match ((t (:background "dodger blue" :foreground "white smoke" :weight bold))))
 '(show-paren-mismatch ((t (:background "orange red" :foreground "white smoke" :weight bold))))
 '(vimish-fold-fringe ((t (:inherit fringe :foreground "black" :weight bold))))
 '(vimish-fold-mouse-face ((t (:background "old lace" :inherit vimish-fold-overlay))))
 '(vimish-fold-overlay ((t (:background "floral white" :foreground "black" :box (:line-width 1 :color "moccasin")))))
 '(warning ((t (:foreground "tomato" :weight bold))))
 '(whitespace-big-indent ((t (:background "orange red" :foreground "white"))))
 '(whitespace-empty ((t (:background "orange red" :foreground "white"))))
 '(whitespace-hspace ((t (:background "orange red" :foreground "white"))))
 '(whitespace-indentation ((t (:background "DodgerBlue3" :foreground "white"))))
 '(whitespace-line ((t (:foreground "orange red"))))
 '(whitespace-newline ((t (:foreground "DodgerBlue4" :weight bold))))
 '(whitespace-space ((t (:foreground "DodgerBlue4" :weight bold))))
 '(whitespace-space-after-tab ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(whitespace-space-before-tab ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(whitespace-tab ((t (:background "floral white" :foreground "black"))))
 '(trailing-whitespace ((t (:underline (:color "tomato" :style wave)))))
 '(hydra-face-blue ((t (:foreground "DodgerBlue3" :weight bold))))
 '(hydra-face-red ((t (:foreground "red2" :weight bold))))
 '(hydra-face-pink ((t (:foreground "DeepPink3" :weight bold))))
 '(hydra-face-teal ((t (:foreground "turquoise4" :weight bold))))
 '(hydra-face-amaranth ((t (:foreground "DarkOrchid3" :weight bold))))
 '(avy-lead-face ((t (:background "gray25" :foreground "white" :weight bold))))
 '(avy-lead-face-0 ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(avy-lead-face-1 ((t (:background "PaleGreen4" :foreground "white" :weight bold))))
 '(avy-lead-face-2 ((t (:background "DeepPink3" :foreground "white" :weight bold))))
 '(avy-background-face ((t (:foreground "gray40"))))
 '(avy-goto-char-timer-face ((t (:inherit (highlight)))))
 '(neo-root-dir-face ((t (:foreground "gray25" :weight bold))))
 '(neo-file-link-face ((((background dark)) (:foreground "White")) (t (:foreground "Black"))))
 '(neo-expand-btn-face ((t (:foreground "DeepPink3" :weight bold))))
 '(neo-banner-face ((((background dark)) (:weight bold :foreground "lightblue")) (t (:foreground "DarkMagenta"))))
 '(neo-header-face ((t (:foreground "gray25"))))
 '(neo-dir-link-face ((t (:foreground "DodgerBlue3" :weight bold)))))

(provide-theme 'clearview-light)
