(deftheme clearview-light
  "Created 2017-03-10.")

(custom-theme-set-faces
 'clearview-light
 '(avy-lead-face ((t (:background "orange red" :foreground "white" :weight bold))))
 '(avy-lead-face-0 ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(avy-lead-face-1 ((t (:background "sea green" :foreground "white" :weight bold))))
 '(avy-lead-face-2 ((t (:background "VioletRed3" :foreground "white" :weight bold))))
 '(cua-rectangle ((t (:background "gray20" :foreground "white"))))
 '(custom-button ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "gray95"))))
 '(custom-button-mouse ((t (:background "DodgerBlue3" :foreground "white" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((t (:box (:line-width 2 :style pressed-button) :inherit custom-button-mouse))))
 '(custom-group-tag ((t (:inherit variable-pitch :background "gray25" :foreground "white smoke" :weight bold :height 1.25))))
 '(custom-modified ((t (:background "DodgerBlue3" :foreground "white"))))
 '(custom-variable-tag ((t (:weight bold))))
 '(flycheck-error ((t (:foreground "red" :underline (:color "firebrick" :style wave)))))
 '(flycheck-error-list-column-number ((t (:inherit default))))
 '(flycheck-error-list-error ((t (:inherit flycheck-fringe-error))))
 '(flycheck-error-list-info ((t (:inherit flycheck-fringe-info))))
 '(flycheck-error-list-line-number ((t (:weight bold))))
 '(flycheck-error-list-warning ((t (:inherit flycheck-fringe-warning))))
 '(flycheck-fringe-error ((t (:foreground "red" :weight bold))))
 '(flycheck-fringe-info ((t (:foreground "forest green" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "DodgerBlue1" :weight bold))))
 '(flycheck-info ((t (:underline (:color "forest green" :style wave)))))
 '(flycheck-warning ((t (:underline (:color "gray30" :style wave)))))
 '(font-lock-builtin-face ((t (:foreground "black" :underline t))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "gray60" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "DarkOrchid2"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-function-name-face ((t (:foreground "DodgerBlue2" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "black" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit font-lock-regexp-grouping-construct))))
 '(font-lock-regexp-grouping-construct ((t nil)))
 '(font-lock-string-face ((t (:foreground "SlateBlue4" :slant normal))))
 '(font-lock-type-face ((t (:foreground "dark slate gray" :weight semi-bold))))
 '(font-lock-variable-name-face ((t (:foreground "black"))))
 '(fringe ((t (:background "grey95"))))
 '(helm-M-x-key ((t (:foreground "purple3" :underline t))))
 '(helm-action ((t nil)))
 '(helm-buffer-directory ((t (:foreground "black" :weight bold))))
 '(helm-buffer-file ((t (:inherit default))))
 '(helm-buffer-not-saved ((t (:slant italic))))
 '(helm-buffer-process ((t (:foreground "gray50"))))
 '(helm-buffer-saved-out ((t (:background "black" :foreground "white smoke"))))
 '(helm-ff-directory ((t (:foreground "black" :weight bold))))
 '(helm-ff-dotted-directory ((t (:inherit helm-ff-directory :underline t))))
 '(helm-ff-executable ((t (:foreground "forest green"))))
 '(helm-ff-file ((t (:inherit default))))
 '(helm-ff-invalid-symlink ((t (:foreground "red"))))
 '(helm-ff-symlink ((t (:foreground "DodgerBlue3"))))
 '(helm-grep-cmd-line ((t (:inherit (diff-added)))))
 '(helm-grep-file ((t (:foreground "black" :underline t))))
 '(helm-grep-finish ((t (:foreground "forest green"))))
 '(helm-grep-lineno ((t (:foreground "gray50"))))
 '(helm-match ((t (:foreground "VioletRed3"))))
 '(helm-moccur-buffer ((t (:foreground "DodgerBlue3" :underline t))))
 '(helm-selection ((t (:background "DodgerBlue3" :foreground "white smoke" :weight bold))))
 '(helm-separator ((t (:foreground "gray60"))))
 '(helm-source-header ((t (:background "gray20" :foreground "white smoke" :weight bold :height 1.25 :family "Sans Serif"))))
 '(helm-swoop-target-line-block-face ((t (:inherit helm-selection))))
 '(helm-swoop-target-line-face ((t (:inherit helm-selection))))
 '(helm-swoop-target-word-face ((t (:inherit lazy-highlight))))
 '(highlight ((t (:background "DarkSeaGreen2" :foreground "black"))))
 '(isearch ((t (:background "VioletRed3" :foreground "white smoke" :weight bold))))
 '(isearch-fail ((t (:background "DodgerBlue3" :foreground "white smoke" :weight bold))))
 '(lazy-highlight ((t (:background "gray20" :foreground "white smoke" :weight bold))))
 '(link ((t (:foreground "dodgerblue" :underline "black"))))
 '(link-visited ((t (:inherit link :foreground "black"))))
 '(minibuffer-prompt ((t (:foreground "black" :underline nil :weight bold))))
 '(mode-line ((t (:background "gray92" :foreground "black" :box (:line-width 1 :color "gray60")))))
 '(mode-line-buffer-id ((t (:weight semi-bold))))
 '(mode-line-inactive ((t (:weight normal :foreground "black" :background "gray95" :inherit mode-line))))
 '(region ((t (:background "gray93" :distant-foreground "black"))))
 '(show-paren-match ((t (:background "dodger blue" :foreground "white smoke" :weight bold))))
 '(show-paren-mismatch ((t (:background "orange red" :foreground "white smoke" :weight bold))))
 '(trailing-whitespace ((t (:background "gray25"))))
 '(vimish-fold-fringe ((t (:inherit fringe :foreground "black" :weight bold))))
 '(vimish-fold-mouse-face ((t (:inherit vimish-fold-overlay :background "old lace"))))
 '(vimish-fold-overlay ((t (:box (:line-width 1 :color "moccasin") :foreground "black" :background "floral white"))))
 '(warning ((t (:foreground "tomato" :weight bold))))
 '(whitespace-big-indent ((t (:background "orange red" :foreground "white"))))
 '(whitespace-empty ((t (:background "orange red" :foreground "white"))))
 '(whitespace-hspace ((t (:background "orange red" :foreground "white"))))
 '(whitespace-indentation ((t (:background "DodgerBlue3" :foreground "white"))))
 '(whitespace-line ((t (:foreground "orange red"))))
 '(whitespace-newline ((t (:foreground "DodgerBlue4" :weight bold))))
 '(whitespace-space ((t (:foreground "DodgerBlue4" :weight bold))))
 '(whitespace-space-after-tab ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(whitespace-space-before-tab ((t (:background "DodgerBlue3" :foreground "white" :weight bold))))
 '(whitespace-tab ((t (:background "floral white" :foreground "black"))))
 '(default ((t (:background "white" :foreground "black")))))

(provide-theme 'clearview-light)
